name: Build
on:
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: ">=1.22.0-rc.1"
      - name: Build
        run: go build -v ./...
      - name: Test
        run: go test -v ./...
  build:
    permissions:
      contents: read
      packages: write
    needs: test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Build
        run: |
          docker build -t ghcr.io/andyleap/blog:${{ github.sha }} .
      - name: Login
        run: |
          echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u $ --password-stdin
      - name: Push
        run: |
          docker push ghcr.io/andyleap/blog:${{ github.sha }}
